name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SSH_USER: timothyefraim35

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH deploy keys
      run: |
        which ssh-agent || ( apt-get install -qq openssh-client )
        eval $(ssh-agent -s)
        ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
        mkdir -p ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  build:
    runs-on: ubuntu-latest
    needs: setup-ssh
    steps:
    - uses: actions/checkout@v3
    - name: SSH to GCE VM and perform "pull github & deploy django" script
      run: ssh $SSH_USER@${{ secrets.SSH_HOST }} "./pull.sh"
