name: Django CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'  

env:
  SSH_USER: timothyefraim35

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH deploy keys
      run: |
        which ssh-agent || ( apt-get install -qq openssh-client )
        eval $(ssh-agent -s)
        ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        ls ~/.ssh
        ssh-copy-id -i ~/.ssh/id_rsa.pub -p 22 $SSH_USER@${{ secrets.SSH_HOST }}
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  build:
    runs-on: ubuntu-latest
    needs: setup-ssh
    steps:
    - uses: actions/checkout@v3
    - name: SSH to GCE VM and perform "pull github & deploy django" script
      run: ssh -v -o StrictHostKeyChecking=no $SSH_USER@${{ secrets.SSH_HOST }} "./pull.sh"
