name: Django CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'  

env:
  SSH_USER: timothyefraim35

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SSH to GCE VM and perform "pull github & deploy django" script
      uses: fifsky/ssh-action@master
      with:
        command: ./pull.sh
        host: ${{ secrets.SSH_HOST }}
        user: $SSH_USER
        key: ${{ secrets.SSH_PRIVATE_KEY }}
